#include <dutch_text_processor.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>

// Int vector initialization.
static void iv_init(IntVec *v) {
    v->data = NULL; v->len = 0; v->cap = 0;
}

// Push the id into Intvec
static void iv_push(IntVec *v, int x) {
    if (v->len + 1 > v->cap) {
        v->cap = v->cap ? v->cap * 2 : 16;
        v->data = realloc(v->data, v->cap * sizeof(int));
        if (!v->data) { perror("realloc"); exit(1); }
    }
    v->data[v->len++] = x;

    
}

// Free the IntVec pointer
static void iv_free(IntVec *v) { free(v->data); v->data = NULL; v->len = v->cap = 0; }


static int cmp_symbol_len_desc(const void *a, const void *b) {
    const SymbolEntry *sa = (const SymbolEntry *)a;
    const SymbolEntry *sb = (const SymbolEntry *)b;
    if (sa->len < sb->len) return 1;
    if (sa->len > sb->len) return -1;
    return 0;
}

// Removing stress marks that generated by espeak (' and ,)
static char *remove_stress_marks(const char *s) {
    size_t n = strlen(s);
    char *out = malloc(n + 1);
    if (!out) { perror("malloc"); exit(1); }

    size_t j = 0;
    for (size_t i = 0; i < n; ) {

        if (s[i] == '\'') {
            i += 1;
            continue;
        }

        if ((unsigned char)s[i] == 0xCB &&
            (unsigned char)s[i+1] == 0x88) {
            i += 2;
            continue;
        }

        if ((unsigned char)s[i] == 0xCB &&
            (unsigned char)s[i+1] == 0x8C) {
            i += 2;
            continue;
        }

        out[j++] = s[i++];
    }

    out[j] = '\0';
    return out;
}

// Replace ipas whitch in NORMALIZE_SRC with NORMALIZE_DST
static char *replace_all(const char *s, const char *old, const char *newstr) {
    size_t s_len = strlen(s);
    size_t old_len = strlen(old);
    size_t new_len = strlen(newstr);
    if (old_len == 0) return strdup(s);

    size_t est_repl = s_len / (old_len ? old_len : 1) + 4;
    size_t cap = s_len + est_repl * (new_len > old_len ? (new_len - old_len) : 0) + 16;
    char *out = malloc(cap);
    if (!out) { perror("malloc"); exit(1); }

    size_t i = 0, o = 0;
    while (i < s_len) {
        if (i + old_len <= s_len && memcmp(s + i, old, old_len) == 0) {
            if (o + new_len + 1 > cap) {
                cap = (cap + new_len + s_len) * 2;
                out = realloc(out, cap);
                if (!out) { perror("realloc"); exit(1); }
            }
            memcpy(out + o, newstr, new_len);
            o += new_len;
            i += old_len;
        } else {
            if (o + 2 > cap) {
                cap = (cap + s_len) * 2;
                out = realloc(out, cap);
                if (!out) { perror("realloc"); exit(1); }
            }
            out[o++] = s[i++];
        }
    }
    out[o] = '\0';
    return out;
}

static char *apply_normalize(const char *ipa) {
    char *cur = strdup(ipa);

    for (size_t k = 0; k < NORMALIZE_COUNT; ++k) {
        char *next = replace_all(cur, NORMALIZE_SRC[k], NORMALIZE_DST[k]);
        free(cur);
        cur = next;
    }
    return cur;
}

// Convert ipas to ids
int ipa_to_ids(char * ipas, IntVec * ids){
    size_t sym_count = sizeof(SYMBOLS_INIT) / sizeof(SYMBOLS_INIT[0]);
    SymbolEntry *symbols = malloc(sym_count * sizeof(SymbolEntry));
    if (!symbols) { perror("malloc"); return 1; }
    for (size_t i = 0; i < sym_count; ++i) {
        symbols[i] = SYMBOLS_INIT[i];
        symbols[i].len = strlen(symbols[i].sym);
    }

    qsort(symbols, sym_count, sizeof(SymbolEntry), cmp_symbol_len_desc);
    
    char *no_stress = remove_stress_marks(ipas);
    
    char *norm = apply_normalize(no_stress);
    free(no_stress);
    
    iv_init(ids);
    
    iv_push(ids, 3);
    const char *p = norm;
    size_t pos = 0;
    size_t n = strlen(norm);
    
    while (pos < n) {
        int matched = 0;
        for (size_t si = 0; si < sym_count; ++si) {
            size_t L = symbols[si].len;
            if (L == 0) continue;
            if (pos + L <= n && memcmp(norm + pos, symbols[si].sym, L) == 0) {
                iv_push(ids, symbols[si].id);
                
                pos += L;
                matched = 1;
                break;
            }
        }
        if (!matched) {
            size_t end = pos + 4; if (end > n) end = n;
            fprintf(stderr, "Unknown IPA sequence at byte position %zu: '", pos);
            free(norm);
            free(symbols);
            iv_free(ids);
            return 1;
        }
    }
    iv_push(ids, 3);
    
    free(norm);
    free(symbols);
    return 0;
}
